services:
  postgres:
    image: postgres:15
    container_name: secureapi_postgres
    environment:
      POSTGRES_USER: secureapi
      POSTGRES_PASSWORD: secureapi
      POSTGRES_DB: secureapi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ..           # assumes Dockerfile is in project root (secureapi/)
      dockerfile: Dockerfile
    container_name: secureapi_api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      APP_ENV: development
      DATABASE_URL_DEV: postgres://secureapi:secureapi@postgres:5432/secureapi?sslmode=disable
      DATABASE_URL_PROD: postgres://secureapi:secureapi@your-production-db:5432/secureapi?sslmode=require

volumes:
  postgres_data:
